fname = input ("Enter First Name: ")
lname = input ("Enter Last Name: ")
mname = input ("Enter Middle Name: ")
dob = input ("Enter Birthday (MM/DD/YYYY): ")
gender = input ("Enter Gender (M/F): ")
add = input ("Enter Address: ")
course = input ("Enter Course: ")
ylevel = input ("Enter Year Level: ")

print ("=======================================")
print ("First Name:", fname)
print ("Last Name:", lname)
print ("Middle Name:", mname)
print ("Birthday:", dob)
print ("Gender:", gender)
print ("Address:", add)
print ("Course:", course)
print ("Year Level:", ylevel)